---
homebrew_installed_packages:
  - autoconf
  - automake
  - bash
  - bash-completion@2
  - bat
  - clang-format
  - cmake
  - cocoapods
  - coreutils
  - dust
  - fd
  - ffmpeg
  - fzf
  - gh
  - go
  - highlight
  - htop
  - imagemagick
  - jq
  - mas
  - maven
  - moreutils
  - neofetch
  - neovim
  - ninja
  - nmap
  - onefetch
  - ripgrep
  - rustup-init
  - starship
  - the_silver_searcher
  - tldr
  - tmux
  - tree
  - vim
  - watchman
  - wget
  - youtube-dl

homebrew_cask_apps:
  - android-studio
  - balenaetcher
  - blackhole-2ch
  - brave-browser-beta
  - docker
  - eloston-chromium
  - firefox-beta
  - font-noto-sans
  - font-sauce-code-pro-nerd-font
  - font-source-code-pro
  - font-ubuntu
  - font-yanone-kaffeesatz
  - gimp
  - google-chrome-beta
  - google-chrome-canary
  - gpg-suite
  - inkscape
  - iterm2
  - joplin
  - karabiner-elements
  - kitty
  - libreoffice
  - logitech-options
  - microsoft-edge-beta
  - nextcloud
  - obs
  - omnidisksweeper
  - plex
  - safari-technology-preview
  - slack
  - spotify
  - thunderbird
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - whatsapp
  - wireshark

mas_installed_apps:
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 533696630, name: "Webcam Settings" }
  - { id: 409183694, name: "Keynote" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1319778037, name: "iStat Menus" }
  - { id: 497799835, name: "Xcode" }
  - { id: 668208984, name: "GIPHY CAPTURE" }

mas_uninstalled_apps:
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }

npm_packages:
  - install-local
  - npm-check-updates
  - react-native-cli

ruby_gems:
  - xcode-tools
