---
homebrew_installed_packages_main:
  - autoconf
  - automake
  - bash
  - bash-completion@2
  - cmake
  - cocoapods
  - coreutils
  - editorconfig
  - go
  - htop
  - jq
  - mas
  - maven
  - moreutils
  - nmap
  - node@10
  - the_silver_searcher
  - tmux
  - vim
  - watchman
  - wget

homebrew_installed_packages_extra:
  - mps-youtube
  - youtube-dl

homebrew_cask_apps_main:
  - xquartz
  - adoptopenjdk8
  - android-studio
  - docker
  - dropbox
  - fastlane
  - firefox-beta
  - firefox-nightly
  - font-noto-sans
  - font-source-code-pro
  - font-source-code-pro-for-powerline
  - font-ubuntu
  - font-yanone-kaffeesatz
  - freesmug-chromium
  - gimp
  - google-chrome-beta
  - google-chrome-canary
  - gpg-suite
  - inkscape
  - iterm2
  - keeweb
  - libreoffice
  - multifirefox
  - omnidisksweeper
  - safari-technology-preview
  - slack
  - thunderbird
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - wireshark

homebrew_cask_apps_extra:
  - nextcloud
  - notable
  - plex-media-player
  - spotify
  - vlc
  - whatsapp

mas_apps_main:
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 533696630, name: "Webcam Settings" }
  - { id: 409183694, name: "Keynote" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1319778037, name: "iStat Menus" }
  - { id: 497799835, name: "Xcode" }

mas_apps_extra:
  - { id: 404360415, name: "Blink Pro" }
  - { id: 896450579, name: "Textual" }
  - { id: 668208984, name: "GIPHY CAPTURE" }

npm_packages:
  - install-local
  - npm-check-updates
  - react-native-cli

pip_packages: []
