---
homebrew_installed_packages:
  - autoconf
  - automake
  - bash
  - bash-completion@2
  - cmake
  - cocoapods
  - coreutils
  - editorconfig
  - htop
  - jq
  - mas
  - maven
  - moreutils
  - nmap
  - the_silver_searcher
  - tmux
  - vim
  - watchman
  - wget
  - youtube-dl

homebrew_cask_apps:
  - android-studio
  - docker
  - eloston-chromium
  - fastlane
  - firefox-beta
  - font-noto-sans
  - font-sauce-code-pro-nerd-font
  - font-source-code-pro
  - font-ubuntu
  - font-yanone-kaffeesatz
  - gimp
  - google-chrome-beta
  - google-chrome-canary
  - gpg-suite
  - inkscape
  - iterm2
  - joplin
  - karabiner-elements
  - libreoffice
  - nextcloud
  - omnidisksweeper
  - plex
  - safari-technology-preview
  - slack
  - spotify
  - thunderbird
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - whatsapp
  - wireshark

mas_apps:
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 533696630, name: "Webcam Settings" }
  - { id: 409183694, name: "Keynote" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1319778037, name: "iStat Menus" }
  - { id: 497799835, name: "Xcode" }
  - { id: 668208984, name: "GIPHY CAPTURE" }

npm_packages:
  - install-local
  - npm-check-updates
  - react-native-cli

pip_packages: []
