---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  tasks:
    - name: Install Homebrew packages
      import_role:
        name: geerlingguy.mac.homebrew
      vars:
        - homebrew_taps:
          - homebrew/core
          - homebrew/cask
          - homebrew/cask-fonts
          - homebrew/cask-versions
        - homebrew_cask_appdir: /Applications
        - homebrew_cask_accept_external_apps: yes
      tags: ['homebrew']

    - name: Install nvm
      become: no
      ansible.builtin.shell: >
        curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
      tags: ['node']

    - name: Install node
      become: no
      shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
      loop:
        - 16
      tags: ['node']

    - name: Install apps from the Mac App Store
      import_role:
        name: geerlingguy.mac.mas
      tags: ['mas']

    - name: Accept Xcode license
      shell: xcodebuild -license accept
      become: yes

    - name: Install extra packages from npm
      import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Apply my macOS defaults
      import_tasks: tasks/macos-defaults.yml
      tags: ['macos-defaults']

    - name: Change user shell
      import_tasks: tasks/shell.yml
      tags: ['shell']
