#!/usr/bin/env bash

set -o nounset
set -o pipefail

yes_or_no() {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0  ;;
            [Nn]*) return 1 ;;
        esac
    done
}

main() {
    # This is script must not be run as root
    if [[ $EUID -eq 0 ]]; then
        echo "This script must NOT be run as root"
        exit 1
    fi

    if [[ ! -d ".venv" ]]; then
        echo "Creating a Python venv..."
        /usr/bin/python3 -m venv .venv
        source .venv/bin/activate
        pip install ansible
    else
        echo "Activating existing venv..."
        source .venv/bin/activate
    fi

    # Now run the playbook
    yes_or_no "Run the playbook?"
    if [[ $? -eq 0 ]]; then
        CHECK_OPT=""
        yes_or_no "Dry run?"
        if [[ $? -eq 0 ]]; then
            CHECK_OPT="--check"
        fi
        echo "Running playbook now, go grab a ☕️"
        ansible-galaxy install -r requirements.yml
        ansible-playbook main.yml -i inventory -K ${CHECK_OPT}
    fi

    deactivate

    # Install dotfiles
    if [[ ! -d "$HOME/.dotfiles" ]]; then
        yes_or_no "Install dotfiles?"
        if [[ $? -eq 0 ]]; then
            git clone --bare https://github.com/saghul/dotfiles.git ~/.dotfiles
            /usr/bin/git \
                --git-dir=$HOME/.dotfiles/ \
                --work-tree=$HOME \
                config --local status.showUntrackedFiles no
            /usr/bin/git \
                --git-dir=$HOME/.dotfiles/ \
                --work-tree=$HOME \
                checkout -f
        fi
    fi
}

main $@
