---
- name: Install global NPM packages.
  community.general.npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
  with_items: "{{ npm_packages }}"

- name: Install Ruby packages.
  community.general.gem:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    user_install: yes
  with_items: "{{ ruby_gems }}"
