---
- name: Add shell to /etc/shells
  lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/bash
    state: present
  become: yes

- name: Change user shell to Homebrew installed Bash
  shell: chsh -s /opt/homebrew/bin/bash "{{ ansible_user_id }}"
  become: yes
